spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fusiontech
    username: fusiontech_user
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

#  jackson:
#    time-zone: "GMT+7"
#        default_schema: 'FUSIONTECH'
