spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true
  #        use_sql_comments: true
  datasource:
  #    url: jdbc:h2:file:tcp://localhost/./fusiontech;mode=mysql;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:h2:file:./fusiontech;mode=mysql;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password:
  h2:
    console:
      enabled: true
      path: /h2
  sql:
    init:
      mode: embedded
logging:
#  file:
#    name: spring.log
  level:
    web: debug
    com:
      vnco: debug
    org:
      springframework:
        web: debug
      hibernate:
        type:
          descriptor:
            sql: trace
  logback:
    rollingpolicy:
      clean-history-on-start: true
#  pattern:
#    console:
#    dateformat: HH:mm
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE
