server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  forward-headers-strategy: framework

#App properties
spring:
  application:
    name: "FusionTech"
  config:
    import:
  profiles:
    active: dev
  jpa:
    open-in-view: false
  mvc:
    problemdetails:
      enabled: true
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: NONE
  data:
    rest:
      base-path: api
  jackson:
    serialization:
      fail-on-empty-beans: false
  security:
    user:
      name: user
      password: user
  servlet:
    multipart:
      max-file-size: '10MB'
      max-request-size: '50MB'
#  main:
#    lazy-initialization: true

management:
  endpoints:
    web:
      exposure:
        include: 'startup'

firebase:
  projectId: "fusiontech-afd82"
  clientId: "1:992997713903:web:99bace107b73424587f81a"
  databaseUrl: "https://console.firebase.google.com/u/1/project/fusiontech-afd82/firestore/data/~2F"
  storageBucket: "fusiontech-afd82.appspot.com"
  apiKey: "AIzaSyDPlncKDneM6FqVrLRpHl8M-UGiIriU16w"
  authDomain: "fusiontech-afd82.firebaseapp.com"
