INSERT INTO brand
SELECT * FROM CSVREAD('data/brand.csv', NULL, 'charset=UTF-8');

INSERT INTO CATEGORY(ID, description, image, name, slug, specifications)
SELECT ID,DESCRIPTION,IMAGE,NAME,SLUG,SPECIFICATIONS FORMAT JSON FROM CSVREAD('data/category.csv', NULL, 'charset=UTF-8');

INSERT INTO PRODUCT
SELECT ID,DESCRIPTION,FEATURES FORMAT JSON ,IMAGES FORMAT JSON ,NAME,SLUG,SUMMARY,BRAND_ID,CATEGORY_ID FROM CSVREAD('data/product.csv', NULL, 'charset=UTF-8');

INSERT INTO PRODUCT_VARIANT
SELECT ID,IMAGES FORMAT JSON ,PRICE,SKU,PRODUCT_ID FROM CSVREAD('data/variant.csv', NULL, 'charset=UTF-8');

INSERT INTO PRODUCT_SPECIFICATION
SELECT *  FROM CSVREAD('data/specification.csv', NULL, 'charset=UTF-8');

INSERT INTO VARIANT_SPECIFICATION
SELECT * FROM CSVREAD('data/variant-specification.csv', NULL, 'charset=UTF-8');
