USE FUSIONTECH;

ALTER TABLE APP_USER ADD COLUMN VERIFIED BOOLEAN DEFAULT FALSE;

ALTER TABLE APP_USER CHANGE VERIFIED IS_VERIFIED BOOLEAN DEFAULT FALSE;

ALTER TABLE PRODUCT_VARIANT MODIFY COLUMN ACTIVE BOOLEAN DEFAULT TRUE;

ALTER TABLE PRODUCT MODIFY COLUMN ACTIVE BOOLEAN DEFAULT TRUE;

UPDATE PRODUCT_VARIANT SET ACTIVE = TRUE;

UPDATE PRODUCT SET ACTIVE = TRUE;

ALTER TABLE REVIEW ADD CONSTRAINT UNIQUE (PRODUCT_ID, USER_ID);

DROP TRIGGER IF EXISTS set_default_address;
DELIMITER  //
CREATE TRIGGER set_default_address
    AFTER INSERT ON SHIPPING_ADDRESS
    FOR EACH ROW
BEGIN
    DECLARE user_address_count INT;

    -- Count the number of addresses for the user
    SELECT COUNT(*) INTO user_address_count
    FROM SHIPPING_ADDRESS
    WHERE user_id = NEW.user_id;

    -- If user has no addresses, set the new address as default
    IF user_address_count = 1 THEN
        UPDATE APP_USER
        SET default_address_id = NEW.id
        WHERE id = NEW.user_id;
    END IF;
END//
DELIMITER ;
