package com.vnco.fusiontech.common.constant;

public interface DBConstant {
    String USER_TABLE = "APP_USER";
    String AUTHORITY_TABLE = "AUTHORITY";
    String ROLE_TABLE = "ROLE";

    String CATEGORY_TABLE = "CATEGORY";
    String BRAND_TABLE = "BRAND";
    String ATTRIBUTE_TABLE = "ATTRIBUTE";
    String REVIEW_TABLE = "REVIEW";
    String SPEC_TABLE = "PRODUCT_SPECIFICATION";
    String PRODUCT_TABLE = "PRODUCT";
    String VARIANT_ATTRIBUTE_TABLE = "PRODUCT_ATTRIBUTE";
    String PRODUCT_VARIANT_TABLE = "PRODUCT_VARIANT";
    String VARIANT_INVENTORY_TABLE = "PRODUCT_VARIANT_INVENTORY";
    String VARIANT_INVENTORY_DETAIL_TABLE = "VARIANT_INVENTORY_DETAIL";
    String FAVORITE_TABLE = "FAVORITE";

    String ORDER_TABLE = "APP_ORDER";
    String ORDER_ITEM_TABLE = "ORDER_ITEM";
    String SHIPPING_ADDRESS_TABLE = "SHIPPING_ADDRESS";
    String PAYMENT_TABLE      = "PAYMENT";
    String VARIANT_SPEC_TABLE = "VARIANT_SPECIFICATION";
    String VOUCHER_TABLE = "VOUCHER";
}
